"""empty message

Revision ID: 18d3f08543ea
Revises: 8d975102ed7f
Create Date: 2022-03-16 04:24:46.198675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18d3f08543ea'
down_revision = '8d975102ed7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('des', sa.String(length=1000), nullable=True))
    op.drop_column('properties', 'dets')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('dets', sa.VARCHAR(length=1000), autoincrement=False, nullable=True))
    op.drop_column('properties', 'des')
    # ### end Alembic commands ###
