"""empty message

Revision ID: 7fbfa0b5c05d
Revises: 108d6ac4aa4f
Create Date: 2019-02-13 23:00:01.066642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbf87930d384'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('properties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=80), nullable=True),
    sa.Column('des', sa.String(length=1000), nullable=True),
    sa.Column('rooms', sa.String(length=20), nullable=True),
    sa.Column('bathrooms', sa.String(length=20), nullable=True),
    sa.Column('price', sa.String(length=100), nullable=True),
    sa.Column('location', sa.String(length=400), nullable=True),
    sa.Column('propType', sa.String(length=30), nullable=True),
    sa.Column('photo', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('properties')
    # ### end Alembic commands ###
